# /workspaces/OP-PSJ/Preroute/.streamlit/secrets.toml
# Base de datos de usuarios
# Las contraseñas aquí están "hasheadas". NUNCA guardes contraseñas en texto plano.
# Usaremos el script generate_keys.py para crear estos hashes.
[users]
admin = { password = "$2b$12$TgSqNkkcx3xoiZvbQTmPoOajSmzK7VyIiXynSaAf1iFpbk309dkKe", role = "admin" }
usuario_comun = { password = "$2b$12$yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy", role = "user" }
invitado = { password = "$2b$12$zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", role = "guest" }

[roles]
# Los nombres aquí deben coincidir con las claves del diccionario PAGES_CONFIG
admin = ["1_🚀_Pre-Route", "2_📊_Dashboard"]
user = ["2_📊_Dashboard"] # Por ejemplo, un usuario normal solo ve el dashboard
